include:
  - compose.volumes.yaml

services:
  web-app:
    extends:
      file: compose.base.yaml
      service: web-app-base
    ports:
      - '3000:3000'
    labels:
      kompose.image-pull-policy: 'Never'
      kompose.service.expose: '${APP_HOSTNAME:-localhost}'

  api:
    extends:
      file: compose.base.yaml
      service: api-base
    ports:
      - '${FASTIFY_PORT:-3001}:${FASTIFY_PORT:-3001}'
    labels:
      kompose.image-pull-policy: 'Never'
      kompose.service.expose: '${API_HOSTNAME:-localhost}${API_ROUTE_PREFIX}'
