services:
  web-app:
    build:
      context: .
      target: web-app
    ports:
      - '3000:3000'
  api:
    build:
      context: .
      target: api
    ports:
      - '3001:3001'
    volumes:
      - db-data:/db

volumes:
  db-data:
