import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import './globals.css'
import { StyledEngineProvider } from '@mui/material/styles'


const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ weight: '400', subsets: ['latin'] })

import AppNavbar from './navbar'
import Providers from './providers'
import RuntimeInit from './runtimeInit'

export const metadata: Metadata = {
  title: 'React Next.js example',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.className}`}>
        <AppRouterCacheProvider>
          <StyledEngineProvider>
            <RuntimeInit>
              <Providers>
                <AppNavbar />
                <div>{children}</div>
              </Providers>
            </RuntimeInit>
          </StyledEngineProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
